### ISSUE TITLE
Update the title of mailing list

### ISSUE THREAD

**Issue by lovincyrus** [HackDavis/website-2019#6]
Mailing list: https://hackdavis.us19.list-manage.com/subscribe/post?u=31b1ac38598fc40775d40347e&id=cb5474d7a8

Issues:
1. CSI Involvement Fair 2018 Signups (irrelevant)
2. Sign up for our mailing list to receive announcements about workshops and events throughout the year! (irrelevant)

**Comment by klanmiko** [comment]
Title has been changed
