### ISSUE TITLE
Update links to apply at console and index.html

### ISSUE THREAD

**Issue by lovincyrus** [HackDavis/website-2019#8]
(1) console.log
https://github.com/HackDavis/website-2019/blob/master/assets/js/main.js#L42

Before: Apply at LINK_TO_APPLY
After: Apply at `https://link-to-apply.com`

(2) `index.html`
https://github.com/HackDavis/website-2019/blob/master/index.html#L4

**Comment by klanmiko** [comment]
will update sometime soon

**Comment by klanmiko** [comment]
done
