### ISSUE TITLE
Landing illustration is not optimized

### ISSUE THREAD

**Issue by lovincyrus** [HackDavis/website-2019#9]
<img width="1440" alt="screen shot 2018-11-14 at 12 06 05 pm" src="https://user-images.githubusercontent.com/1021101/48509361-c0af6200-e805-11e8-8ea3-85cdf8fcdf48.png">

Issues:
+ The svg file is pixelated on Safari — Version 12.0 (14606.1.36.1.9)
+ could replace with PNG file

**Comment by klanmiko** [comment]
Gonna scale down the resolution of most images as well and replace the landing with a png.

**Comment by lovincyrus** [comment]
I wasn't sure if you knew this feature by Netlify:
<img width="912" alt="screen shot 2018-11-14 at 7 58 36 pm" src="https://user-images.githubusercontent.com/1021101/48529393-c0d05180-e847-11e8-85f8-98e511e278a8.png">

you could also use https://squoosh.app/ to optimize the PNGs.

**Comment by klanmiko** [comment]
I mean lower the resolution before compressing it haha

**Comment by lovincyrus** [comment]
Fixed https://github.com/HackDavis/website-2019/pull/2
